### ISSUE TITLE
你好，VS2019 下无法编译

### ISSUE THREAD

**Issue by williamXDB** [balloonwj/WebSocketServer#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'arpa/inet.h': No such file or directory	WebSocketServer	D:\GitRes\WebSocketServer\base\Platform.h	75	
经测试，win32模式下可以，win64不能编译，请问要怎样才能支持win64?

**Comment by williamXDB** [comment]
加入项目之后，报错：
1>uafxcwd.lib(afxmem.obj) : warning LNK4006: "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) already defined in LIBCMTD.lib(new_scalar.obj); second definition ignored
1>uafxcwd.lib(afxmem.obj) : warning LNK4006: "void __cdecl operator delete(void *)" (??3@YAXPEAX@Z) already defined in LIBCMTD.lib(delete_scalar.obj); second definition ignored
1>uafxcwd.lib(afxmem.obj) : warning LNK4006: "void * __cdecl operator new[](unsigned __int64)" (??_U@YAPEAX_K@Z) already defined in LIBCMTD.lib(new_array.obj); second definition ignored
1>uafxcwd.lib(afxmem.obj) : warning LNK4006: "void __cdecl operator delete[](void *)" (??_V@YAXPEAX@Z) already defined in LIBCMTD.lib(delete_array.obj); second definition ignored
1>   Creating library D:\Work\SameScreen\ScreenServer\x64\Debug\ScreenServer.lib and object D:\Work\SameScreen\ScreenServer\x64\Debug\ScreenServer.exp

**Comment by balloonwj** [comment]
仿照x32的设置配置一下就ok了。
