### ISSUE TITLE
Android提交websocket/http，无法握手通过

### ISSUE THREAD

**Issue by williamXDB** [balloonwj/WebSocketServer#2]
这是此程序最大的瑕疵

**Comment by balloonwj** [comment]
@williamXDB 你的握手内容发一下。

**Comment by williamXDB** [comment]
是这样的，Android提交的时候没有 
Origin: http://127.0.0.1:8001
我跟踪了一下，因为Origin头为空，才导至握手失败的


















在 2021-05-06 12:09:11，"balloonwj" ***@***.***> 写道：

@williamXDB 你的握手内容发一下。

**Comment by williamXDB** [comment]
> @williamXDB 你的握手内容发一下。

测试起来很简单，用你的websocket服务器，开启之后，用Android连上去(用Android app程序，自带的websocket连接），一连就崩了，ios则需要设置一些参数，
最后通过系列跟踪才发现，问题出在android app通过自带websocket连接上去时，没有orign头，于是websocket握手验证失败，
当时试了几个方案，伪造websocket头，加入orign头，或修改产生的密文等，结果一一失败，
后来选择了boost自带的websocket

**Comment by balloonwj** [comment]
那你一下不就可以了嘛，这个又不难。
