### ISSUE TITLE
＠作者，请问bug修正了吗？

### ISSUE THREAD

**Issue by williamXDB** [balloonwj/WebSocketServer#3]
＠balloonwj,
 问题 解决了吗？我倒是可以测试验证一下呢

**Comment by williamXDB** [comment]
巨汗，作者，问题依旧，安装一连接就断了，哎，失望啊

**Comment by williamXDB** [comment]
![服务端被android一连就断开](https://user-images.githubusercontent.com/12944753/145048858-87892359-860f-4e5c-90b3-aa54f8ab8faa.png)

**Comment by williamXDB** [comment]
![握手不通过](https://user-images.githubusercontent.com/12944753/145049890-8a1a68ba-b454-4944-89bd-0bf0334894fd.png)

**Comment by williamXDB** [comment]
同样的移动端，poco/boost/libwebsocket  websocket做服务端，都不会出这样的问题

**Comment by balloonwj** [comment]
操作不当，请自查。

**Comment by balloonwj** [comment]
操作不当，请自查。

**Comment by williamXDB** [comment]
这种心态，真是无敌了 ，要给你竖大拇指了……
